package de.ruu.app.jeeeraaah.frontend.ui.fx.task.selector;

import static java.util.Objects.isNull;
import static javafx.scene.control.SelectionMode.SINGLE;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import de.ruu.app.jeeeraaah.common.api.bean.TaskBean;
import de.ruu.app.jeeeraaah.common.api.bean.TaskGroupBean;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.TreeCellFactory;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.TreeItemTaskBean;
import de.ruu.lib.fx.comp.FXCController.DefaultFXCController;
import de.ruu.lib.fx.control.autocomplete.textfield.TextFieldAutoCompleteClearableWithArrowButton;
import de.ruu.lib.fx.control.autocomplete.textfield.TextFieldAutoCompleteClearableWithArrowButtonBuilder;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.ReadOnlyObjectProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.fxml.FXML;
import javafx.scene.control.Tab;
import javafx.scene.control.TreeItem;
import javafx.scene.control.TreeView;
import javafx.scene.layout.HBox;
import lombok.NonNull;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2025.08.14 09:59:47:114
 */
@Slf4j
class TaskSelectorController
		extends DefaultFXCController<TaskSelector, TaskSelectorService>
		implements TaskSelectorService
{
	@FXML private TreeView<TaskBean> trVw;
	@FXML private HBox               hBxAutoCompleteTextField;
	@FXML private Tab                tabList;
	@FXML private Tab                tabTree;

	private TextFieldAutoCompleteClearableWithArrowButton<TaskBean> textField;

	private ObjectProperty<TaskBean> selection = new SimpleObjectProperty<>();

	@Override @FXML protected void initialize()
	{
		trVw.setCellFactory(TreeCellFactory.cellFactory());
		trVw.setShowRoot(false);
		trVw.setRoot(new TreeItemTaskBean(new TaskBean(new TaskGroupBean("root"), "root")));

		trVw.getSelectionModel().setSelectionMode(SINGLE);
		trVw.getSelectionModel().selectedItemProperty().addListener((obs, old, act) -> onSelectedTreeItemChanged(act));
	}

	@Override public void populateFor(@NonNull TaskGroupBean taskGroup)
	{
		populateTreeWith                 (taskGroup);
		populateAutoCompleteTextFieldWith(taskGroup);
	}

	@Override public ReadOnlyObjectProperty<TaskBean> selectionChangedProperty() { return selection; }

	private void populateTreeWith(TaskGroupBean taskGroup)
	{
		trVw.getRoot().getChildren().clear(); // clear previous content
		Optional<Set<TaskBean>> optionalAllTasks = taskGroup.tasks();
		if (optionalAllTasks.isPresent())
		{
			// Filter for tasks without super task (main tasks) to build the hierarchy
			List<TaskBean> mainTasksAsList = optionalAllTasks.get().stream()
					.filter(task -> task.superTask().isEmpty())
					.sorted((t1, t2) -> t1.name().compareTo(t2.name()))
					.toList();
			mainTasksAsList.forEach
			(
					mainTask -> trVw.getRoot().getChildren().add(populateTreeNode(trVw.getRoot(), mainTask))
			);
		}
		log.debug("populate tree view done");
	}

	private TreeItem<TaskBean> populateTreeNode(TreeItem<TaskBean> root, TaskBean task)
	{
		return populateTreeNode(root, task, new HashSet<>());
	}

	private TreeItem<TaskBean> populateTreeNode(TreeItem<TaskBean> root, TaskBean task, Set<Long> processedTaskIds)
	{
		// Prevent infinite recursion by tracking already processed tasks
		if (task.id() != null && processedTaskIds.contains(task.id()))
		{
			log.warn("Circular reference detected: Task {} (ID: {}) already in hierarchy - skipping",
					task.name(), task.id());
			return null;
		}

		if (task.id() != null)
		{
			processedTaskIds.add(task.id());
		}

		TreeItem<TaskBean> result = new TreeItem<>(task) { @Override public String toString() { return task.name(); } };
		task.subTasks().ifPresent(subTasks -> populateTreeNode(result, subTasks, processedTaskIds));
		return result;
	}

	private void onSelectedTreeItemChanged(TreeItem<TaskBean> act)
	{
		if (isNull(act)) selection.setValue(null);           // no task selected
		else             selection.setValue(act.getValue()); // task selected
	}

	private void populateTreeNode(TreeItem<TaskBean> parent, Set<TaskBean> children)
	{
		populateTreeNode(parent, children, new HashSet<>());
	}

	private void populateTreeNode(TreeItem<TaskBean> parent, Set<TaskBean> children, Set<Long> processedTaskIds)
	{
		List<TaskBean> childrenAsList = new ArrayList<>(children);
		childrenAsList.sort((o1, o2) -> o1.name().compareTo(o2.name()));
		childrenAsList.forEach(task -> {
			TreeItem<TaskBean> childNode = populateTreeNode(parent, task, processedTaskIds);
			if (childNode != null)
			{
				parent.getChildren().add(childNode);
			}
		});
	}

	private void populateAutoCompleteTextFieldWith(TaskGroupBean taskGroup)
	{
		Optional<Set<TaskBean>> optionalAllTasks = taskGroup.tasks();

		optionalAllTasks.ifPresent
		(
				allTasks ->
				{
					// Use all tasks directly, sorted by name
					List<TaskBean> tasks = new ArrayList<>(allTasks);
					tasks.sort((t1, t2) -> t1.name().compareTo(t2.name()));

					textField =
							TextFieldAutoCompleteClearableWithArrowButtonBuilder.<TaskBean>create()
									.items           (tasks.stream().sorted((t1, t2) -> t1.name().compareTo(t2.name())).toList())
									.suggestionFilter((task, text) -> task.name().toLowerCase().contains(text.toLowerCase()))
									.textProvider    (task -> task.name())
									.prompt          ("select successor task")
									.build();

					textField.setMaxWidth(Double.MAX_VALUE);
					HBox.setHgrow(textField, javafx.scene.layout.Priority.ALWAYS);

					hBxAutoCompleteTextField.getChildren().clear();
					hBxAutoCompleteTextField.getChildren().add(textField);
					textField.valueProperty().addListener((obs, old, val) -> selection.setValue(val));
				}
		);
	}

	private void collectTaskWithSubTasks(TaskBean task, List<TaskBean> tasks)
	{
		collectTaskWithSubTasks(task, tasks, new HashSet<>());
	}

	private void collectTaskWithSubTasks(TaskBean task, List<TaskBean> tasks, Set<Long> processedTaskIds)
	{
		if (task.id() != null && processedTaskIds.contains(task.id()))
		{
			log.warn("Circular reference detected in collectTaskWithSubTasks: Task {} (ID: {}) already processed",
					task.name(), task.id());
			return;
		}

		tasks.add(task);
		if (task.id() != null)
		{
			processedTaskIds.add(task.id());
		}
		task.subTasks().ifPresent(subTasks -> subTasks.forEach(subTask -> collectTaskWithSubTasks(subTask, tasks, processedTaskIds)));
	}
}
