<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>r-uu</groupId>
	<artifactId>r-uu.app.jeeeraaah.bom</artifactId>
	<version>0.0.1</version>
	<packaging>pom</packaging>
	<name>${project.artifactId}</name>
	<description>bill of material for jeeeraaah application — extends r-uu.bom, adds lombok/mapstruct/annotation-processors and all jeeeraaah/lib-specific modules</description>

	<parent>
		<groupId>r-uu</groupId>
		<artifactId>r-uu.bom</artifactId>
		<version>0.0.1</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<properties>
		<version.lombok>1.18.42</version.lombok>
		<version.lombok-mapstruct-binding>0.2.0</version.lombok-mapstruct-binding>
		<version.mapstruct>1.6.3</version.mapstruct>
		<version.hibernate-jpamodelgen>6.6.5.Final</version.hibernate-jpamodelgen>
	</properties>

	<dependencyManagement>
		<dependencies>

			<!-- ################################### -->
			<!-- Lombok + MapStruct + JPA model gen -->
			<!-- ################################### -->
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${version.lombok}</version>
				<scope>provided</scope>
				<optional>true</optional>
			</dependency>
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok-mapstruct-binding</artifactId>
				<version>${version.lombok-mapstruct-binding}</version>
				<scope>provided</scope>
				<optional>true</optional>
			</dependency>
			<dependency>
				<groupId>org.mapstruct</groupId>
				<artifactId>mapstruct</artifactId>
				<version>${version.mapstruct}</version>
			</dependency>
			<dependency>
				<groupId>org.mapstruct</groupId>
				<artifactId>mapstruct-processor</artifactId>
				<version>${version.mapstruct}</version>
			</dependency>
			<dependency>
				<groupId>org.hibernate.orm</groupId>
				<artifactId>hibernate-jpamodelgen</artifactId>
				<version>${version.hibernate-jpamodelgen}</version>
				<scope>provided</scope>
			</dependency>

			<!-- ######################## -->
			<!-- jeeeraaah app modules   -->
			<!-- ######################## -->
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.backend.common.mapping_jpa_dto</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.backend.persistence.jpa</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.common.api.bean</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.common.api.domain</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.common.api.mapping</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.common.api.ws_rs</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.frontend.ui.fx_model</artifactId>
				<version>${project.version}</version>
			</dependency>

			<!-- jeeeraaah aggregator poms -->
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.backend</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.backend.api</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.backend.api.open-liberty</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.backend.api.open-liberty.shared</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.backend.api.ws_rs</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.backend.common</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.backend.persistence</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.common</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.common.api</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.frontend</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.frontend.api_client</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.frontend.api_client.ws_rs</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.frontend.common</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.frontend.common.mapping_bean_fxbean</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.frontend.ui</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.frontend.ui.fx</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.app.jeeeraaah.frontend.ui.fx_executable</artifactId>
				<version>${project.version}</version>
			</dependency>

			<!-- ######################################### -->
			<!-- library modules (jeeeraaah/lib specific) -->
			<!-- ######################################### -->
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.cdi.se.demo</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.docker_health</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.gen</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.gen.core</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.gen.java</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.gen.java.core</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.gen.java.fx</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.gen.java.fx.bean</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.gen.java.fx.bean_editor</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.gen.java.fx.bean_editor_demo</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.gen.java.fx.comp</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.gen.java.fx.tableview</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.jackson</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.jasperreports</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.jasperreports.client</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.jasperreports.server</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.jdbc</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.jdbc.core</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.jdbc.postgres</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.jpa.core_mapstruct</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.jpa.core_mapstruct_demo_bidirectional</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.jpa.core_mapstruct_test</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.jpa.se</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.jpa.se_hibernate</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.jpa.se_hibernate_postgres</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.jpa.se_hibernate_postgres_demo</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.jsonb</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.keycloak_admin</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.mapstruct</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.mapstruct.spi</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.mp_config</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.office</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.office.word</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.postgres</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.postgres_util_ui</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.lib.ws_rs</artifactId>
				<version>${project.version}</version>
			</dependency>

			<!-- ####### -->
			<!-- sandbox -->
			<!-- ####### -->
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.sandbox</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.sandbox.jasperreports</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.sandbox.jasperreports.example</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.sandbox.jasperreports.model</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.sandbox.office</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.sandbox.office.microsoft</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.sandbox.office.microsoft.word</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>r-uu</groupId>
				<artifactId>r-uu.sandbox.office.microsoft.word.docx4j</artifactId>
				<version>${project.version}</version>
			</dependency>

		</dependencies>
	</dependencyManagement>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<configuration>
						<annotationProcessorPaths>
							<path>
								<groupId>org.projectlombok</groupId>
								<artifactId>lombok</artifactId>
								<version>${version.lombok}</version>
							</path>
							<path>
								<groupId>org.projectlombok</groupId>
								<artifactId>lombok-mapstruct-binding</artifactId>
								<version>${version.lombok-mapstruct-binding}</version>
							</path>
							<path>
								<groupId>org.mapstruct</groupId>
								<artifactId>mapstruct-processor</artifactId>
								<version>${version.mapstruct}</version>
							</path>
							<path>
								<groupId>org.hibernate.orm</groupId>
								<artifactId>hibernate-jpamodelgen</artifactId>
								<version>${version.hibernate-jpamodelgen}</version>
							</path>
						</annotationProcessorPaths>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

</project>
