package de.ruu.app.jeeeraaah.frontend.ui.fx.task.hierarchy;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link Hierarchies}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2025.03.20 12:21:07:903
 */
public class Hierarchies extends DefaultFXCView<Hierarchies, HierarchiesService, HierarchiesController>
{
	/**
	 * Provides public access to the controller.
	 * This is needed to call controller methods after the view has been initialized.
	 *
	 * @return the controller instance
	 */
	public HierarchiesController getController() { return controller(); }
}

