package de.ruu.app.jeeeraaah.frontend.ui.fx.task.hierarchy;

import de.ruu.lib.cdi.se.EventDispatcher;
import de.ruu.lib.fx.comp.FXCService;
import de.ruu.lib.util.AbstractEvent;
import jakarta.enterprise.context.ApplicationScoped;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2025.03.20 12:21:07:961
 */
public interface HierarchiesService extends FXCService
{
	/** Event that is fired to indicate that a {@link HierarchiesService} component has become available. */
	public class HierarchiesComponentReadyEvent extends AbstractEvent<Hierarchies, HierarchiesService>
	{
		public HierarchiesComponentReadyEvent(final Hierarchies component, final HierarchiesService service)
		{
			super(component, service);
		}

		/** programmatically specify command line vm option {@code --add-reads de.ruu.lib.fx.comp=ALL-UNNAMED} */
		public static void addReadsUnnamedModule()
		{
			HierarchiesComponentReadyEvent
					.class
					.getModule()
					.addReads(HierarchiesComponentReadyEvent.class.getClassLoader().getUnnamedModule());
		}

		@ApplicationScoped
		public static class HierarchiesComponentReadyEventDispatcher extends EventDispatcher<HierarchiesComponentReadyEvent>
		{
		}
	}
}

