package de.ruu.app.jeeeraaah.frontend.ui.fx.task.hierarchy;

import de.ruu.lib.fx.comp.FXCAppRunner;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import de.ruu.lib.postgres.toolbox.ui.PostgresBackupUIService.PostgresBackupUIReadyEvent;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link HierarchiesAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2025.03.20 12:21:07:988
 * <p>
 * Note: Must be {@code public class} to be accessible from exec-maven-plugin running in unnamed module.
 */
@Slf4j
public class HierarchiesAppRunner extends FXCAppRunner
{
	public static void main(String[] args) throws ClassNotFoundException
	{
		log.debug("starting {}", HierarchiesAppRunner.class.getName());

		// Set config file path if not already set (portable solution)
		if (System.getProperty("config.file.name") == null)
		{
			System.setProperty("config.file.name", "../../../testing.properties");
		}

		FXCAppStartedEvent        .addReadsUnnamedModule();
		PostgresBackupUIReadyEvent.addReadsUnnamedModule();
		HierarchiesAppRunner      .addReadsUnnamedModule();
		FXCAppRunner.run(HierarchiesApp.class, args);
		log.debug("finished {}", HierarchiesAppRunner.class.getName());
	}

	public static void addReadsUnnamedModule()
	{
		HierarchiesAppRunner
				.class
				.getModule()
				.addReads(HierarchiesAppRunner.class.getClassLoader().getUnnamedModule());
	}
}

