package de.ruu.app.jeeeraaah.frontend.ui.fx.task.hierarchy;

import de.ruu.app.jeeeraaah.common.api.bean.TaskBean;
import de.ruu.app.jeeeraaah.common.api.bean.TaskGroupBean;
import de.ruu.app.jeeeraaah.common.api.domain.flat.TaskGroupFlat;
import de.ruu.app.jeeeraaah.frontend.api.client.ws.rs.TaskGroupServiceClient;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.predecessor.TaskHierarchyPredecessors;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.successor.TaskHierarchySuccessors;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.supersub.TaskHierarchySuperSubTasks;
import de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup.TaskGroupManagement;
import de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup.selector.TaskGroupSelector;
import de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup.selector.TaskGroupSelectorService.TaskGroupSelectorComponentReadyEvent;
import de.ruu.app.jeeeraaah.frontend.ui.fx.util.ServiceOperationExecutor;
import de.ruu.lib.cdi.se.EventDispatcher;
import de.ruu.lib.fx.FXUtil;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import de.ruu.lib.fx.comp.FXCController.DefaultFXCController;
import de.ruu.lib.fx.control.dialog.AlertDialog;
import de.ruu.lib.fx.control.dialog.ExceptionDialog;
import de.ruu.lib.postgres.toolbox.ui.PostgresBackupUI;
import de.ruu.lib.ws_rs.NonTechnicalException;
import de.ruu.lib.ws_rs.TechnicalException;
import jakarta.annotation.Nullable;
import jakarta.enterprise.context.Dependent;
import jakarta.inject.Inject;
import javafx.application.Platform;
import javafx.beans.property.ReadOnlyObjectProperty;
import javafx.beans.value.ObservableValue;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.Parent;
import javafx.scene.control.*;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.HBox;
import javafx.stage.Stage;
import lombok.NonNull;
import lombok.extern.slf4j.Slf4j;

import java.util.List;
import java.util.Optional;
import java.util.Set;

import static de.ruu.app.jeeeraaah.common.api.domain.Task.COMPARATOR;
import static de.ruu.lib.fx.FXUtil.getStage;
import static java.util.Objects.isNull;
import static java.util.Objects.requireNonNull;
import static javafx.scene.control.ButtonType.OK;
import static javafx.scene.layout.Priority.ALWAYS;
import static javafx.stage.Modality.APPLICATION_MODAL;

// Removed imports: javafx.stage.Modality, javafx.stage.Stage

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2025.03.20 12:21:07:964
 */
@Slf4j
@Dependent // Explicit: FXML controller lifecycle managed by FXMLLoader, not CDI
class HierarchiesController extends DefaultFXCController<Hierarchies, HierarchiesService> implements HierarchiesService
{
	@FXML private HBox hBxGroupSelector;

	@FXML private AnchorPane nchrPnPredecessors;
	@FXML private AnchorPane nchrPnSuperSubTasks;
	@FXML private AnchorPane nchrPnSuccessors;

	@FXML private Button buttonManageGroups;
	@FXML private Button buttonGantt;

	@FXML private Button buttonBackup;

	@FXML private Button buttonExit;

	// cannot use @Observes(IF_EXISTS) directly because @Dependent beans don't support conditional observers
	@Inject private EventDispatcher<FXCAppStartedEvent> appStartedEventDispatcher;
	@Inject private EventDispatcher<TaskGroupSelectorComponentReadyEvent> taskGroupSelectorReadyEventDispatcher;

	// inject components that are used in the user interface
	@Inject private TaskGroupSelector taskGroupSelector;

	@Inject private TaskHierarchyPredecessors taskHierarchyPredecessors;
	@Inject private TaskHierarchySuperSubTasks taskHierarchySuperSubTasks;
	@Inject private TaskHierarchySuccessors taskHierarchySuccessors;

	// inject service clients that are used to fetch data from the server
	@Inject private TaskGroupServiceClient taskGroupServiceClient;

	// inject the centralized executor for service operations with session retry handling
	@Inject private ServiceOperationExecutor executor;

	@Inject private TaskGroupManagement taskGroupManagement;
	@Inject private de.ruu.app.jeeeraaah.frontend.ui.fx.task.gantt.Gantt gantt;
	@Inject private PostgresBackupUI postgresBackupUI;

	@Nullable private TaskGroupFlat selectedTaskGroupDTOFlat = null;

	private Parent taskGroupManagementLocalRoot;
	private Parent ganttLocalRoot;

	/**
	 * <ul>
	 *   <li>register listeners to all required dispatchers:
	 *     <ul>
	 *       <li>{@link #appStartedEventDispatcher} - fired when app is fully started (sets window title)
	 *       <li>{@link #taskGroupSelectorReadyEventDispatcher} - fired when task group selector is ready
	 *     </ul>
	 *   <li>force ui components to initialise themselves by calling their localRoot() methods and
	 *       compose the ui by adding their return values into the ui containers
	 *   <li>register listeners to all button actions
	 *   <li>register listener to {@link #taskHierarchySuperSubTasks} selection changed actions
	 *   <li>fetch all task groups from the backend and populate the task group selector
	 * </ul>
	 *
	 * @see DefaultFXCController#initialize()
	 */
	@Override
	@FXML
	protected void initialize()
	{
		appStartedEventDispatcher.add(this::onAppStarted);
		taskGroupSelectorReadyEventDispatcher.add(this::onTaskGroupSelectorReady);

		// force task group management to initialise itself and store its local root
		taskGroupManagementLocalRoot = taskGroupManagement.localRoot();
		ganttLocalRoot = gantt.localRoot();

		// force task group selector to initialise itself and compose its local root into the ui
		HBox.setHgrow(taskGroupSelector.localRoot(), ALWAYS);
		hBxGroupSelector.getChildren().add(taskGroupSelector.localRoot());

		// force task hierarchy views to initialise themselves and add their local roots to the anchor panes
		nchrPnPredecessors.getChildren().add(taskHierarchyPredecessors.localRoot());
		nchrPnSuperSubTasks.getChildren().add(taskHierarchySuperSubTasks.localRoot());
		nchrPnSuccessors.getChildren().add(taskHierarchySuccessors.localRoot());

		FXUtil.setAnchorsInAnchorPaneTo(taskHierarchyPredecessors.localRoot(), 0);
		FXUtil.setAnchorsInAnchorPaneTo(taskHierarchySuperSubTasks.localRoot(), 0);
		FXUtil.setAnchorsInAnchorPaneTo(taskHierarchySuccessors.localRoot(), 0);

		// register listeners to all button actions
		buttonManageGroups.setOnAction(e -> onManageGroups());
		buttonGantt.setOnAction(e -> onGantt());
		buttonBackup.setOnAction(this::onBackup);
		buttonExit.setOnAction(this::onExit);

		// register listener to task hierarchy super/sub tasks selection changed actions
		taskHierarchySuperSubTasks.service().selectedItem()
				.addListener(this::onSelectedSuperSubTaskChanged);

		// NOTE: Data loading moved to loadInitialData() method
		// This is called after authentication is complete in HierarchiesApp.start()
	}

	/**
	 * Loads initial data from backend after authentication is complete.
	 *
	 * <p>This method is called from HierarchiesApp.start() AFTER the user has been authenticated.
	 * It must not be called from initialize() because authentication happens after FXML loading.</p>
	 */
	public void loadInitialData()
	{
		log.info("Loading initial data from backend...");
		fetchTaskGroupsFromBackendAndPopulateTaskGroupSelector();
	}

	private void fetchTaskGroupsFromBackendAndPopulateTaskGroupSelector()
	{
		try
		{
			Set<TaskGroupFlat> groups = executor.execute(
					() -> taskGroupServiceClient.findAllFlat(),
					"fetching task groups",
					"Failed to load task groups",
					"Load failed after re-login"
			);

			// now we are ready to hand over the groups to groupSelector
			taskGroupSelector.service().items(groups);
		} catch (TechnicalException | NonTechnicalException e)
		{
			log.error("failure fetching task groups from backend", e);
			ExceptionDialog.showAndWait("failure fetching task groups from backend", e);
		}
	}

	/**
	 * is called as soon as the task group selector is available, performs various initialisations that depend on
	 * task group selector.
	 *
	 * @param e the event that indicates that the groupSelector component is ready
	 */
	private void onTaskGroupSelectorReady(TaskGroupSelectorComponentReadyEvent e)
	{
		Platform.runLater(() -> {
			@NonNull ReadOnlyObjectProperty<TaskGroupFlat> selectedTaskGroupProperty =
					taskGroupSelector.service().selectedTaskGroupProperty();

			// make sure the listener method is called whenever the selected group in groupSelector changes
			selectedTaskGroupProperty.addListener((obs, old, act) -> onSelectedTaskGroupChanged(act));
		});
	}

	private void onSelectedTaskGroupChanged(TaskGroupFlat actSelection)
	{
		selectedTaskGroupDTOFlat = actSelection;

		if (isNull(actSelection)) return;

		// fetch the task group with its tasks and their neighbour tasks from the server
		try
		{
			Optional<TaskGroupBean> optional = executor.execute(
					() -> taskGroupServiceClient.findWithTasksAndDirectNeighbours(requireNonNull(actSelection.id())),
					"fetching task group details for id: " + actSelection.id(),
					"Failed to load task group details",
					"Load failed after re-login"
			);

			if (optional.isPresent())
			{
				TaskGroupBean taskGroupBean = optional.get();

				// collect root tasks (without super task), sorted
				List<TaskBean> mainTasks = taskGroupBean.tasks()
						.map(tasks -> tasks.stream()
								.filter(taskBean -> taskBean.superTask().isEmpty())
								.sorted(COMPARATOR)
								.toList())
						.orElse(List.of());

				taskHierarchyPredecessors .service().populate(List.of()); // clear predecessors
				taskHierarchySuperSubTasks.service().populate(mainTasks); // populate super/subs
				taskHierarchySuccessors   .service().populate(List.of()); // clear successors

				taskHierarchySuperSubTasks.service().focusRootItem();

				taskHierarchyPredecessors .service().activeTaskGroupProperty().set(taskGroupBean);
				taskHierarchySuperSubTasks.service().activeTaskGroupProperty().set(taskGroupBean);
				taskHierarchySuccessors   .service().activeTaskGroupProperty().set(taskGroupBean);

				taskHierarchySuperSubTasks.service().activeTaskGroupProperty()
						.addListener((obs, old, act) -> onActiveTaskPropertyChangedInSuperSubTaskHierarchy(act));
			}
			else log.debug("no lazy group could be retrieved");
		}
		catch (TechnicalException | NonTechnicalException e)
		{
			ExceptionDialog.showAndWait("failure fetching task group from backend", e);
		}
	}

	/**
	 * Called when the FX application has fully started.
	 * Sets the window title after all components are initialized.
	 */
	private void onAppStarted(FXCAppStartedEvent e)
	{
		getStage(hBxGroupSelector).ifPresent(s -> s.setTitle("jeee RAAAH - task hierarchies"));
	}

	private void onManageGroups()
	{
		// Refresh data before showing the dialog
		taskGroupManagement.service().refreshData();

		Dialog<Void> dialog = new Dialog<>();
		dialog.setTitle("manage task groups");
		dialog.setResizable(true);
		assignOwnerTo(dialog);
		dialog.initModality(APPLICATION_MODAL);

		DialogPane pane = dialog.getDialogPane();
		pane.setContent(taskGroupManagementLocalRoot);
		pane.getButtonTypes().add(OK);

		dialog.showAndWait();

		// refresh task groups after management dialog is closed
		fetchTaskGroupsFromBackendAndPopulateTaskGroupSelector();
	}

	private void assignOwnerTo(Dialog<Void> dialog)
	{
		getStage(buttonManageGroups).ifPresent
		(
				s ->
				{
					dialog.initOwner(s);
					log.info("assigned owner of dialog to {}", s.getTitle());
				}
		);
	}

	private void onGantt()
	{
		Dialog<Void> dialog = new Dialog<>();
		dialog.setTitle("gantt chart");
		dialog.setResizable(true);
		assignOwnerTo(dialog);
		dialog.initModality(APPLICATION_MODAL);

		DialogPane pane = dialog.getDialogPane();
		pane.setContent(ganttLocalRoot);
		pane.getButtonTypes().add(OK);

		// ensure Gantt data is loaded
		gantt.service().loadInitialData();

		dialog.showAndWait();
	}

	private void onBackup(ActionEvent event)
	{
		Dialog<Void> dialog = new Dialog<>();
		dialog.setTitle("PostgreSQL Backup");
		dialog.setResizable(true);
		assignOwnerTo(dialog);
		dialog.initModality(APPLICATION_MODAL);

		// create dialog pane and add PostgresBackupUI
		DialogPane dialogPane = dialog.getDialogPane();
		dialogPane.setContent(postgresBackupUI.localRoot());

		// add close button
		ButtonType closeButtonType = new ButtonType("Close", ButtonType.CLOSE.getButtonData());
		dialogPane.getButtonTypes().add(closeButtonType);

		// show dialog
		dialog.showAndWait();
	}

	private void onExit(ActionEvent event)
	{
		AlertDialog.showAndWait("not yet implemented");
	}

	private void onSelectedSuperSubTaskChanged(
			ObservableValue<? extends TreeItem<TaskBean>> obs, TreeItem<TaskBean> old, TreeItem<TaskBean> act)
	{
		taskHierarchyPredecessors.service().selectedSuperSubTaskTreeItemChanged(act);
		taskHierarchySuccessors  .service().selectedSuperSubTaskTreeItemChanged(act);
	}

	/**
	 * Whenever the active task group changes in the super/sub task hierarchy view, we have to set the new active task
	 * group in the predecessor and successor hierarchy views, too, to propagate possible changes in the active
	 * {@link TaskGroupBean#tasks()}.
	 *
	 * @param act the new active task group
	 */
	private void onActiveTaskPropertyChangedInSuperSubTaskHierarchy(TaskGroupBean act)
	{
		taskHierarchyPredecessors.service().activeTaskGroupProperty().set(act);
		taskHierarchySuccessors  .service().activeTaskGroupProperty().set(act);
	}
}