package de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup;

import static de.ruu.lib.fx.FXUtil.getStage;
import static javafx.scene.control.ButtonBar.ButtonData.OK_DONE;
import static javafx.scene.control.ButtonType.CANCEL;
import static javafx.scene.control.ButtonType.OK;

import java.util.Objects;
import java.util.Optional;

import de.ruu.app.jeeeraaah.common.api.bean.TaskGroupBean;
import de.ruu.app.jeeeraaah.common.api.domain.TaskGroupLazy;
import de.ruu.app.jeeeraaah.common.api.mapping.bean_flat.TaskGroupMapper;
import de.ruu.app.jeeeraaah.frontend.api.client.ws.rs.TaskGroupServiceClient;
import de.ruu.app.jeeeraaah.frontend.common.mapping.bean.fxbean.Map_TaskGroup_Bean_FXBean;
import de.ruu.app.jeeeraaah.frontend.common.mapping.fxbean.bean.Map_TaskGroup_FXBean_Bean;
import de.ruu.app.jeeeraaah.frontend.ui.fx.model.TaskGroupFXBean;
import de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup.edit.TaskGroupEditor;
import de.ruu.lib.cdi.common.CDIUtil;
import de.ruu.lib.cdi.se.EventDispatcher;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import de.ruu.lib.fx.comp.FXCController.DefaultFXCController;
import de.ruu.lib.fx.control.dialog.ExceptionDialog;
import de.ruu.lib.mapstruct.ReferenceCycleTracking;
import de.ruu.lib.ws.rs.NonTechnicalException;
import de.ruu.lib.ws.rs.TechnicalException;
import jakarta.annotation.PostConstruct;
import jakarta.enterprise.context.Dependent;
import jakarta.inject.Inject;
import javafx.beans.value.ObservableValue;
import javafx.fxml.FXML;
import javafx.scene.Parent;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.Dialog;
import javafx.scene.control.DialogPane;
import javafx.scene.control.TableView;
import javafx.scene.control.TextArea;
import javafx.scene.control.ToolBar;
import javafx.scene.image.ImageView;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;
import lombok.NonNull;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2024.10.12 07:54:38:618
 */
@Slf4j @Dependent // Explicit: FXML controller lifecycle managed by FXMLLoader, not CDI
// Note: Must be @Dependent (default) - FXML controllers are instantiated by FXMLLoader.
// @FXML fields injected after construction but before initialize(), incompatible with @ApplicationScoped.
class TaskGroupManagementController extends DefaultFXCController<TaskGroupManagement, TaskGroupManagementService>
		implements TaskGroupManagementService
{
	private final static String APP_TITLE = "jeee RAAAH - task group management";

	@Inject
	private EventDispatcher<FXCAppStartedEvent> appStartedEventDispatcher;

	@FXML
	private Button btnAdd;
	@FXML
	private Button btnEdit;
	@FXML
	private Button btnExit;
	@FXML
	private Button btnRemove;

	@FXML
	private ImageView ivwAdd;
	@FXML
	private ImageView ivwEdit;
	@FXML
	private ImageView ivwRemove;
	@FXML
	private ImageView ivwExit;

	@FXML
	private AnchorPane root;
	@FXML
	private ToolBar tbr1;
	@FXML
	private ToolBar tbr2;
	@FXML
	private TableView<TaskGroupFXBean> tv;
	@FXML
	private TextArea txtAreaDescription;
	@FXML
	private VBox vbx;

	@Inject
	private TaskGroupEditor editor;
	@Inject
	private TaskGroupServiceClient client;

	private Parent editorLocalRoot;

	@Override @FXML
	protected void initialize()
	{
		// force editor to fxml-inject internal fx-controls
		editorLocalRoot = editor.localRoot();

		TableViewConfigurator.configure(tv);
		ReferenceCycleTracking context = new ReferenceCycleTracking();
		try
		{
			client.findAllFlat().forEach(
					flat -> {
						TaskGroupBean bean = TaskGroupMapper.INSTANCE.toBean(flat);
						TaskGroupFXBean fxBean = Map_TaskGroup_Bean_FXBean.INSTANCE.map(bean, context);
						tv.getItems().add(fxBean);
					});
		}
		catch (TechnicalException | NonTechnicalException e)
		{
			ExceptionDialog.showAndWait("failure retrieving task groups from backend", e);
		}

		tv.getSelectionModel().selectedItemProperty()
				.addListener((obs, old, val) -> onSelectedTaskGroupChanged(obs, old, val));
		btnAdd .setOnAction(e -> onAdd());
		btnEdit.setOnAction(e -> onEdit());
		btnExit.setOnAction(e -> onExit());

		getStage(root).ifPresent(s -> s.setTitle(APP_TITLE));
	}

	@PostConstruct
	private void registerEventListeners()
	{
		appStartedEventDispatcher.add(this::onAppStarted);
	}

	private void onSelectedTaskGroupChanged(ObservableValue<? extends TaskGroupFXBean> obs, TaskGroupFXBean old,
			TaskGroupFXBean val)
	{
		if (Objects.isNull(val))
		{
			txtAreaDescription.setText("");
			btnEdit.setDisable(true);
		}
		else
		{
			val.description().ifPresentOrElse(d -> txtAreaDescription.setText(d), () -> txtAreaDescription.setText(""));
			btnEdit.setDisable(false);
		}
	}

	private void onAdd()
	{
		ReferenceCycleTracking context = new ReferenceCycleTracking();
		// populate editor with new item, call to getService() has to be done after call to getLocalRoot() to make sure
		// internal java fx bindings can be established (see initialize)
		TaskGroupBean taskGroupBean = new TaskGroupBean("new task group");
		TaskGroupFXBean taskGroupFXBean = Map_TaskGroup_Bean_FXBean.INSTANCE.map(taskGroupBean, context);
		editor.service().taskGroup(taskGroupFXBean);

		Dialog<TaskGroupFXBean> dialog = new Dialog<>();

		DialogPane pane = dialog.getDialogPane();
		pane.setContent(editorLocalRoot);
		pane.getButtonTypes().addAll(CANCEL, OK);

		dialog.setTitle("new task group");
		dialog.setResultConverter(this::dialogResultConverterFXBean);

		Optional<TaskGroupFXBean> optional = dialog.showAndWait();

		if (optional.isPresent())
		{
			taskGroupFXBean = optional.get();
			taskGroupBean = Map_TaskGroup_FXBean_Bean.INSTANCE.map(taskGroupFXBean, context);

			// let client create a new item in backend
			try
			{
				taskGroupBean = client.create(taskGroupBean);
				// create fx bean from entity dto
				taskGroupFXBean = Map_TaskGroup_Bean_FXBean.INSTANCE.map(taskGroupBean, context);
				// add and select item with retrieved item
				tv.getItems().add(taskGroupFXBean);
				tv.getSelectionModel().select(taskGroupFXBean);
			}
			catch (TechnicalException | NonTechnicalException e)
			{
				ExceptionDialog.showAndWait("failure creating task groups in backend", e);
			}
		}
	}

	private void onEdit()
	{
		ReferenceCycleTracking context = new ReferenceCycleTracking();
		// populate editor with selected item, call to getService() has to be done after call to getLocalRoot() to make sure
		// internal java fx bindings can be established (see initialize)
		TaskGroupFXBean taskGroupFXBean = tv.getSelectionModel().getSelectedItem();
		editor.service().taskGroup(taskGroupFXBean);

		Dialog<TaskGroupFXBean> dialog = new Dialog<>();

		DialogPane pane = dialog.getDialogPane();
		pane.setContent(editorLocalRoot);
		pane.getButtonTypes().addAll(CANCEL, OK);

		dialog.setTitle("edit task group");
		dialog.setResultConverter(this::dialogResultConverterFXBean);

		Optional<TaskGroupFXBean> optional = dialog.showAndWait();

		if (optional.isPresent())
		{
			taskGroupFXBean = optional.get();
			TaskGroupBean taskGroupBean = Map_TaskGroup_FXBean_Bean.INSTANCE.map(optional.get(), context);

			// let client update the item in background
			try
			{
				taskGroupBean = client.update(taskGroupBean);
				// create fx bean from entity dto
				taskGroupFXBean = Map_TaskGroup_Bean_FXBean.INSTANCE.map(taskGroupBean, context);
				// add and select item with retrieved item
				tv.getSelectionModel().select(taskGroupFXBean);
			}
			catch (TechnicalException | NonTechnicalException e)
			{
				ExceptionDialog.showAndWait("failure updating task groups in backend", e);
			}
		}
	}

	private void onExit()
	{
		CDIUtil.fire(new TaskGroupManagementDisposeRequestEvent(this));
	}

	private TaskGroupFXBean dialogResultConverterFXBean(ButtonType btn)
	{
		if (btn.getButtonData() == OK_DONE)
			return editor.service().taskGroup().orElse(null);
		return null;
	}

	/**
	 * Called when the FX application has started.
	 */
	private void onAppStarted(FXCAppStartedEvent e)
	{
		getStage(root).ifPresent(s -> s.setTitle(APP_TITLE));
	}
}