package de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.successor;

import de.ruu.app.jeeeraaah.common.api.bean.TaskBean;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.TaskHierarchyControllerAbstract;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.successor.add.ActionAdd;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.successor.add.ActionAdd.Context;
import de.ruu.app.jeeeraaah.frontend.api.client.ws.rs.TaskServiceClient;
import de.ruu.lib.fx.control.dialog.AlertDialog;
import de.ruu.lib.fx.control.dialog.ExceptionDialog;
import de.ruu.lib.ws.rs.NonTechnicalException;
import de.ruu.lib.ws.rs.TechnicalException;
import jakarta.annotation.Nullable;
import jakarta.inject.Inject;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.TreeItem;
import lombok.extern.slf4j.Slf4j;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import static de.ruu.lib.util.BooleanFunctions.not;
import static java.util.Objects.isNull;
import static javafx.geometry.NodeOrientation.LEFT_TO_RIGHT;
import static javafx.geometry.NodeOrientation.RIGHT_TO_LEFT;
import static javafx.scene.control.Alert.AlertType.ERROR;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2025.06.03 12:49:45:376
 */
@Slf4j
class TaskHierarchySuccessorsController
		extends TaskHierarchyControllerAbstract implements TaskHierarchySuccessorsService
{
	@Inject private TaskServiceClient taskServiceClient;

	private ObjectProperty<TreeItem<TaskBean>> selectedSuperSubTaskTreeItemProperty = new SimpleObjectProperty<>();
	private ObjectProperty<TreeItem<TaskBean>> selectedSuccessorTreeItemProperty    = new SimpleObjectProperty<>();

	@Override @FXML protected void initialize()
	{
		super.initialize();

//		treeView().setNodeOrientation(LEFT_TO_RIGHT); // default
		treeView().getSelectionModel().selectedItemProperty()
				.addListener((obs, old, act) -> selectedSuccessorTreeItemProperty.set(act));

		buttonAdd   ().disableProperty()
				.bind(selectedSuperSubTaskTreeItemProperty.isNull().and(selectedSuccessorTreeItemProperty.isNull()));
		buttonRemove().disableProperty()
				.bind(selectedSuperSubTaskTreeItemProperty.isNull().and(selectedSuccessorTreeItemProperty.isNull()));

		buttonAdd   ().setOnAction(e -> onAdd   (e));
		buttonRemove().setOnAction(e -> onRemove(e));
	}

	@Override public void selectedSuperSubTaskTreeItemChanged(@Nullable TreeItem<TaskBean> selectedSuperSubTaskTreeItem)
	{
		selectedSuperSubTaskTreeItemProperty.set(selectedSuperSubTaskTreeItem);;

		treeView().getRoot().getChildren().clear(); // clear the successor tree view
		taskView.service().unpopulateView();

		if (isNull(selectedSuperSubTaskTreeItem))
				return;

		if (selectedSuperSubTaskTreeItem.getValue().successors().isPresent())
		{
			Set<TaskBean> successors = selectedSuperSubTaskTreeItem.getValue().successors().get();
			successors.forEach
			(
					successor -> treeView().getRoot().getChildren().add(populateTreeNode(treeView().getRoot(), successor))
			);
		}
	}

	@Override protected void onAdd(ActionEvent e)
	{
		if (isNull(selectedSuperSubTaskTreeItemProperty) && isNull(selectedSuccessorTreeItemProperty))
		{
			AlertDialog.showAndWait
			(
					"can not add successor relation",
					"no successor nor super/sub task is selected",
					"select a successor and/or a super/sub task as target for the new successor relation",
					ERROR
			);
			return;
		}

		new ActionAdd
		(
				new Context
				(
						selectedSuperSubTaskTreeItemProperty.get(),
						selectedSuccessorTreeItemProperty.get() == null
								? treeView().getRoot()
								: selectedSuccessorTreeItemProperty.get(),
						taskServiceClient
				)
		).execute();
	}

	@Override protected void onRemove(ActionEvent e)
	{
		if (isNull(selectedSuccessorTreeItemProperty.get()))
		{
			AlertDialog.showAndWait
			(
					"can not remove successor relation",
					"no successor task is selected",
					"select a successor task to be removed",
					ERROR
			);
			return;
		}

		TaskBean selectedSuccessor = selectedSuccessorTreeItemProperty.get().getValue();

		if (    selectedSuccessor.successors().isPresent() &&
				not(selectedSuccessor.successors().get().isEmpty()))
		{
			AlertDialog.showAndWait
			(
					"can not remove successor relation",
					"the selected successor task has successor relations",
					"remove the successor relations first, then you can remove this successor relation",
					ERROR
			);
			return;
		}

		if (selectedSuccessor.predecessors().isPresent())
		{
			Exception exception = null;
			// remove selected successor for all it's predecessors
			for (TaskBean predecessor : selectedSuccessor.predecessors().get())
			{
				// - remove the predecessor-predecessor relation in the db
				try
				{
					taskServiceClient.removeSuccessor(predecessor, selectedSuccessor);
				}
				catch (TechnicalException | NonTechnicalException ex)
				{
					exception = ex;
					break;
				}
			}

			if (not(isNull(exception)))
			{
				ExceptionDialog.showAndWait("failure removing successor", exception);
				return;
			}

			// remove the predecessor-successor relation in the ui model
			TreeItem<TaskBean> parent = selectedSuccessorTreeItemProperty.get().getParent();
			if (parent != null) parent.getChildren().remove(selectedSuccessorTreeItemProperty);
		}
	}

	@Override protected TreeItem<TaskBean> populateTreeNode(TreeItem<TaskBean> root, TaskBean task)
	{
		return populateTreeNode(root, task, new HashSet<>());
	}

	private TreeItem<TaskBean> populateTreeNode(TreeItem<TaskBean> root, TaskBean task, Set<Long> processedTaskIds)
	{
		// Prevent infinite recursion by tracking already processed tasks
		if (task.id() != null && processedTaskIds.contains(task.id()))
		{
			log.warn("Circular reference detected: Task {} (ID: {}) already in hierarchy - skipping to prevent infinite loop",
					task.name(), task.id());
			return null;
		}

		if (task.id() != null)
		{
			processedTaskIds.add(task.id());
		}

		TreeItem<TaskBean> result = new TreeItem<>(task)
		{
			@Override public String toString() { return task.name(); }
		};
		task.successors().ifPresent(successors -> populateTreeNode(result, successors, processedTaskIds));
		return result;
	}

	private void populateTreeNode(TreeItem<TaskBean> result, Set<TaskBean> tasks)
	{
		populateTreeNode(result, tasks, new HashSet<>());
	}

	private void populateTreeNode(TreeItem<TaskBean> result, Set<TaskBean> tasks, Set<Long> processedTaskIds)
	{
		List<TaskBean> tasksAsList = new ArrayList<>(tasks);
		tasksAsList.sort((o1, o2) -> o1.name().compareTo(o2.name()));
		tasksAsList.forEach(task -> {
			TreeItem<TaskBean> childNode = populateTreeNode(result, task, processedTaskIds);
			if (childNode != null)
			{
				result.getChildren().add(childNode);
			}
		});
	}
}
