package de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.successor;

import de.ruu.app.jeeeraaah.common.api.bean.TaskBean;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.TaskHierarchyService;
import jakarta.annotation.Nullable;
import javafx.scene.control.TreeItem;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2025.06.03 12:49:45:374
 */
public interface TaskHierarchySuccessorsService extends TaskHierarchyService
{
	/**
	 * This method is called by a controller (like {@code de.ruu.app.jeeeraaah.frontend.ui.fx.task.hierarchy.HierarchiesController}) when
	 * it observes a change in the selected super/sub task tree item.
	 *
	 * @param treeItem
	 */
	void selectedSuperSubTaskTreeItemChanged(@Nullable TreeItem<TaskBean> treeItem);
}