package de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup.selector;

import java.util.Set;

import de.ruu.app.jeeeraaah.common.api.domain.flat.TaskGroupFlat;
import de.ruu.app.jeeeraaah.common.api.ws.rs.TaskGroupDTOFlat;
import de.ruu.lib.cdi.se.EventDispatcher;
import de.ruu.lib.fx.comp.FXCService;
import de.ruu.lib.util.AbstractEvent;
import jakarta.enterprise.context.ApplicationScoped;
import javafx.beans.property.ReadOnlyObjectProperty;
import lombok.NonNull;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2025.03.20 16:56:31:294
 */
public interface TaskGroupSelectorService extends FXCService
{
	/** @return The currently selected task group as {@link TaskGroupDTOFlat} property. */
	@NonNull
	ReadOnlyObjectProperty<TaskGroupFlat> selectedTaskGroupProperty();

	/** Set the available task groups (as {@link TaskGroupDTOFlat} instances) to select from. */
	void items(@NonNull Set<TaskGroupFlat> groups);

	void updateItem(@NonNull TaskGroupFlat updatedTaskGroup);

	/** Event that is fired to indicate that a {@link TaskGroupSelector} component has become available. */
	class TaskGroupSelectorComponentReadyEvent extends AbstractEvent<TaskGroupSelector, TaskGroupSelectorService>
	{
		public TaskGroupSelectorComponentReadyEvent(final TaskGroupSelector component, final TaskGroupSelectorService service)
		{
			super(component, service);
		}

		/** programmatically specify command line vm option {@code --add-reads de.ruu.lib.fx.comp=ALL-UNNAMED} */
		public static void addReadsUnnamedModule()
		{
			TaskGroupSelectorComponentReadyEvent.class.getModule()
					.addReads(TaskGroupSelectorComponentReadyEvent.class.getClassLoader().getUnnamedModule());
		}

		@ApplicationScoped
		public static class TaskGroupSelectorComponentReadyEventDispatcher
				extends EventDispatcher<TaskGroupSelectorComponentReadyEvent>
		{
		}
	}
}
