package de.ruu.app.jeeeraaah.frontend.ui.fx;

import static de.ruu.lib.fx.FXUtil.getStage;

import de.ruu.app.jeeeraaah.frontend.ui.fx.dash.Dash;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.TaskManagement;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.gantt.GanttTable;
import de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup.TaskGroupManagement;
import de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup.TaskGroupManagementDisposeRequestEvent;
import de.ruu.lib.cdi.se.EventDispatcher;
import de.ruu.lib.fx.FXUtil;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import de.ruu.lib.fx.comp.FXCController.DefaultFXCController;
import jakarta.annotation.PostConstruct;
import jakarta.enterprise.context.Dependent;
import jakarta.inject.Inject;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2024.10.11 17:28:37:119
 */
@Slf4j @Dependent // Explicit: FXML controller lifecycle managed by FXMLLoader, not CDI
// Note: @Dependent scope required - FXML controller instantiated by FXMLLoader, not CDI.
// EventDispatcher pattern used because @Observes(IF_EXISTS) requires @ApplicationScoped.
class MainController extends DefaultFXCController<Main, MainService> implements MainService
{
	private final static String APP_TITLE = "jeee---RAAAH";

	// EventDispatcher pattern for event subscription - alternative to @Observes for @Dependent beans
	@Inject
	private EventDispatcher<FXCAppStartedEvent> appStartedEventDispatcher;
	@Inject
	private EventDispatcher<TaskGroupManagementDisposeRequestEvent> taskGroupManagerDisposeRequestEventDispatcher;

	@FXML
	private Button btnDash;
	@FXML
	private Button btnTaskGroups;
	@FXML
	private Button btnTasksByGroup;
	@FXML
	private Button btnGantt;
	@FXML
	private Label lblJeeeRaaah;
	@FXML
	private VBox main;
	@FXML
	private AnchorPane root;

	@Inject
	private Dash dash;
	@Inject
	private TaskGroupManagement taskGroupManagement;
	@Inject
	private TaskManagement taskManagement;
	@Inject
	private GanttTable ganttTable;

	@Override @FXML
	protected void initialize()
	{
		btnDash.setOnAction(e -> onDash(e));
		btnTaskGroups.setOnAction(e -> onTaskGroups(e));
		btnTasksByGroup.setOnAction(e -> onTasksByGroup(e));
		btnGantt.setOnAction(e -> onGantt(e));
	}

	@PostConstruct
	private void registerEventListeners()
	{
		appStartedEventDispatcher.add(this::onAppStarted);
		taskGroupManagerDisposeRequestEventDispatcher.add(this::onTaskGroupManagerExitRequested);
	}

	private void onDash(ActionEvent e)
	{
		ObservableList<Node> mainRootChildren = root.getChildren();
		Parent dashRoot = dash.localRoot();

		mainRootChildren.remove(main);
		mainRootChildren.add(dashRoot);

		FXUtil.setAnchorsInAnchorPaneTo(dashRoot, 0);

		getStage(root).ifPresent(s -> s.setTitle(APP_TITLE + " - dash"));
	}

	private void onTaskGroups(ActionEvent e)
	{
		ObservableList<Node> mainRootChildren = root.getChildren();
		Parent taskGroupManagementRoot = taskGroupManagement.localRoot();

		mainRootChildren.remove(main);
		mainRootChildren.add(taskGroupManagementRoot);

		FXUtil.setAnchorsInAnchorPaneTo(taskGroupManagementRoot, 0);

		getStage(root).ifPresent(s -> s.setTitle(APP_TITLE + " - task groups"));
	}

	private void onTasksByGroup(ActionEvent e)
	{
		ObservableList<Node> mainRootChildren = root.getChildren();
		Parent taskManagementRoot = taskManagement.localRoot();

		mainRootChildren.remove(main);
		mainRootChildren.add(taskManagementRoot);

		FXUtil.setAnchorsInAnchorPaneTo(taskManagementRoot, 0);

		getStage(root).ifPresent(s -> s.setTitle(APP_TITLE + " - tasks"));
	}

	private void onGantt(ActionEvent e)
	{
		ObservableList<Node> mainRootChildren = root.getChildren();
		Parent ganttTableRoot = ganttTable.localRoot();

		mainRootChildren.remove(main);
		mainRootChildren.add(ganttTableRoot);

		FXUtil.setAnchorsInAnchorPaneTo(ganttTableRoot, 0);

		getStage(root).ifPresent(s -> s.setTitle(APP_TITLE + " - gantt"));
	}

	private void onTaskGroupManagerExitRequested(TaskGroupManagementDisposeRequestEvent e)
	{
		ObservableList<Node> mainRootChildren = root.getChildren();

		mainRootChildren.remove(taskGroupManagement.localRoot());
		mainRootChildren.add(main);

		FXUtil.setAnchorsInAnchorPaneTo(main, 0);
	}

	private void onAppStarted(FXCAppStartedEvent e)
	{
		getStage(root).ifPresent(s -> s.setTitle(APP_TITLE));
	}
}