package de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy;

import static de.ruu.app.jeeeraaah.frontend.common.mapping.Mappings.toBean;
import static de.ruu.app.jeeeraaah.frontend.common.mapping.Mappings.toFXBean;
import static de.ruu.lib.util.BooleanFunctions.not;
import static java.util.Objects.isNull;
import static javafx.scene.control.ButtonBar.ButtonData.OK_DONE;
import static javafx.scene.control.ButtonType.CANCEL;
import static javafx.scene.control.ButtonType.OK;
import static javafx.scene.control.SelectionMode.SINGLE;
import static lombok.AccessLevel.PROTECTED;

import java.util.List;
import java.util.Optional;

import de.ruu.app.jeeeraaah.common.api.bean.TaskBean;
import de.ruu.app.jeeeraaah.common.api.bean.TaskGroupBean;
import de.ruu.app.jeeeraaah.frontend.api.client.ws.rs.TaskServiceClient;
import de.ruu.app.jeeeraaah.frontend.ui.fx.model.TaskFXBean;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.TreeCellFactory;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.TreeItemTaskBean;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.edit.TaskEditor;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.TaskViewNarrow;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.TaskViewNarrowQualifier;
import de.ruu.lib.fx.comp.FXCController.DefaultFXCController;
import de.ruu.lib.fx.control.dialog.ExceptionDialog;
import de.ruu.lib.mapstruct.ReferenceCycleTracking;
import de.ruu.lib.ws_rs.NonTechnicalException;
import de.ruu.lib.ws_rs.TechnicalException;
import jakarta.inject.Inject;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.Parent;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.Dialog;
import javafx.scene.control.DialogPane;
import javafx.scene.control.TreeItem;
import javafx.scene.control.TreeView;
import javafx.scene.layout.VBox;
import lombok.Getter;
import lombok.NonNull;
import lombok.experimental.Accessors;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2025.06.03 12:49:45:376
 */
@Slf4j
@Accessors(fluent = true)
public abstract class TaskHierarchyControllerAbstract
		extends DefaultFXCController<TaskHierarchyAbstract, TaskHierarchyService>
		implements TaskHierarchyService
{
	@FXML private VBox vBox;

	@Getter(PROTECTED) @FXML private TreeView<TaskBean> treeView;
	@Getter(PROTECTED) @FXML private Button             buttonAdd;
	@Getter(PROTECTED) @FXML private Button             buttonRemove;

	@FXML private Button buttonEdit;

//	@Inject private TaskGroupServiceClient taskGroupServiceClient;
	@Inject private TaskServiceClient taskServiceClient;
	@Inject private TaskEditor        taskEditor;

	@TaskViewNarrowQualifier
	@Inject protected TaskViewNarrow taskView;

	/** updated by callers of #activateTaskGroup() */
	private ObjectProperty<TaskGroupBean> activeTaskGroupProperty = new SimpleObjectProperty<>();
	/** updated by #onSelectedTaskChanged() */
	private ObjectProperty<TaskBean>      selectedTaskProperty    = new SimpleObjectProperty<>();

	private Parent taskEditorLocalRoot;

	@Override @FXML protected void initialize()
	{
		// force task group editor to initialise itself and store its local root so that it can be used in
		// onAdd(...) and onEdit(immediately
		taskEditorLocalRoot = taskEditor.localRoot();

		vBox.getChildren().add(taskView.localRoot());

		treeView.setCellFactory(TreeCellFactory.cellFactory());
		treeView.setShowRoot(false);
		treeView.setRoot(new TreeItemTaskBean(new TaskBean(new TaskGroupBean("root"), "root")));

		treeView.getSelectionModel().setSelectionMode(SINGLE);
		treeView.getSelectionModel().selectedItemProperty().addListener((obs, old, act) -> onSelectedTaskChanged(act));

		buttonAdd   .disableProperty().bind(activeTaskGroupProperty.isNull());
		buttonEdit  .disableProperty().bind(selectedTaskProperty   .isNull());
		buttonRemove.disableProperty().bind(selectedTaskProperty   .isNull());

		buttonAdd   .setOnAction(e -> onAdd   (e));
		buttonEdit  .setOnAction(e -> onEdit  (e));
		buttonRemove.setOnAction(e -> onRemove(e));
	}

	@Override public void populate(@NonNull List<TaskBean> tasks)
	{
		treeView.getRoot().getChildren().clear();      // clear previous content
//		treeView.getSelectionModel().clearSelection(); // clear previous selection and trigger repopulation of task view
		tasks.forEach(task -> treeView.getRoot().getChildren().add(populateTreeNode(treeView.getRoot(), task)));
		log.debug("populate tree view done");
	}

	// TODO: move this method to utility class
	@Override public void focusRootItem()
	{
		if (not(treeView.getRoot().isLeaf()) && not(treeView.getRoot().getChildren().isEmpty()))
		{
			TreeItem<TaskBean> firstItem = treeView.getRoot().getChildren().getFirst();
			int                firstRow  = treeView.getRow (firstItem);

			if (firstRow >= 0)
			{
				treeView.getSelectionModel().select(firstRow);
				treeView.getFocusModel().focus(firstRow);
				treeView.requestFocus();
			}
		}
	}

	@Override public ObjectProperty<TaskGroupBean> activeTaskGroupProperty() { return activeTaskGroupProperty; }

	/** override this method to implement the populate tree node functionality specifically to the actual task hierarchy */
	protected abstract TreeItem<TaskBean> populateTreeNode(TreeItem<TaskBean> root, TaskBean task);

	/** override this method to implement the add functionality specifically to the actual task hierarchy */
	protected abstract void onAdd(ActionEvent e);

	private void onEdit(ActionEvent e)
	{
		TaskBean selectedTaskBean = selectedTaskProperty.get();

		if (isNull(selectedTaskBean))
				return; // should never happen because button edit should be disabled in this case and hence this method should
				        // not be called

		// there is a selected task item, so we can edit it, first create a fx-bean from the bean
		TaskFXBean selectedTaskFXBean = toFXBean(selectedTaskBean, new ReferenceCycleTracking());

		taskEditor.service().task(selectedTaskFXBean);

		Dialog<TaskFXBean> dialog     = new Dialog<>();
		DialogPane         dialogPane = dialog.getDialogPane();

		dialog    .setTitle("edit task");
		dialog    .setResultConverter(buttonType -> dialogResultConverterTaskFXBean(buttonType));
		dialogPane.setContent(taskEditorLocalRoot);
		dialogPane.getButtonTypes().addAll(CANCEL, OK);

		Optional<TaskFXBean> optional = dialog.showAndWait();

		if (optional.isPresent())
		{
			selectedTaskFXBean = optional.get();
			selectedTaskBean   = toBean(selectedTaskFXBean, new ReferenceCycleTracking());

			try
			{
				selectedTaskBean = taskServiceClient.update(selectedTaskBean);

				// Update the TreeItem with the updated bean
				TreeItem<TaskBean> selectedItem = treeView.getSelectionModel().getSelectedItem();
				if (not(isNull(selectedItem)))
				{
					selectedItem.setValue(selectedTaskBean);
				}

				taskView.service().populateViewFor(selectedTaskFXBean);
				selectedTaskProperty.set(selectedTaskBean);
			}
			catch (TechnicalException | NonTechnicalException ex)
			{
				ExceptionDialog.showAndWait("failure updating task\n\n" + selectedTaskBean + "\n\n in backend", ex);
			}
		}
	}

	/** override this method to implement the remove functionality specifically to the actual task hierarchy */
	protected abstract void onRemove(ActionEvent e);

	private void onSelectedTaskChanged(TreeItem<TaskBean> act)
	{
		if (isNull(act))
		{
			selectedTaskProperty.set(null); // update selected task
			taskView.service().unpopulateView();
		}
		else
		{
			selectedTaskProperty.set(act.getValue()); // update selected task
			taskView.service().populateViewFor(toFXBean(act.getValue(), new ReferenceCycleTracking()));
		}
	}

	private TaskFXBean dialogResultConverterTaskFXBean(ButtonType buttonType)
	{
		if (buttonType.getButtonData() == OK_DONE) return taskEditor.service().task().orElse(null);
		return null;
	}
}