package de.ruu.app.jeeeraaah.frontend.ui.fx.task.gantt;

import de.ruu.app.jeeeraaah.common.api.domain.TaskGroupFlat;
import de.ruu.app.jeeeraaah.frontend.api.client.ws.rs.TaskGroupServiceClient;
import de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup.selector.TaskGroupSelector;
import de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup.selector.TaskGroupSelectorService.TaskGroupSelectorComponentReadyEvent;
import de.ruu.app.jeeeraaah.frontend.ui.fx.util.ServiceOperationExecutor;
import de.ruu.lib.cdi.se.EventDispatcher;
import de.ruu.lib.fx.FXUtil;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import de.ruu.lib.fx.comp.FXCController;
import de.ruu.lib.fx.control.dialog.ExceptionDialog;
import de.ruu.lib.ws.rs.NonTechnicalException;
import de.ruu.lib.ws.rs.TechnicalException;
import jakarta.enterprise.context.Dependent;
import jakarta.inject.Inject;
import javafx.beans.property.ReadOnlyObjectProperty;
import javafx.fxml.FXML;
import javafx.geometry.Pos;
import javafx.scene.control.Button;
import javafx.scene.control.DatePicker;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Region;
import javafx.scene.layout.VBox;
import javafx.util.StringConverter;
import lombok.NonNull;
import lombok.extern.slf4j.Slf4j;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Optional;
import java.util.Set;

import static de.ruu.lib.fx.FXUtil.getStage;
import static java.util.Objects.isNull;
import static javafx.scene.layout.Priority.ALWAYS;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2025.12.18 18:03:02:243
 */
@Slf4j
@Dependent // Explicit: FXML controller lifecycle managed by FXMLLoader, not CDI
// Note: @Dependent scope (default) is required for FXML controllers because:
// 1. FXMLLoader creates instances - not CDI
// 2. @FXML fields are injected AFTER construction, before initialize()
// 3. @ApplicationScoped would cause NullPointerException when accessing @FXML fields in initialize()
// 4. Cannot use @Observes(IF_EXISTS) with @Dependent, hence EventDispatcher pattern
class GanttController extends FXCController.DefaultFXCController<Gantt, GanttService> implements GanttService
{
//	@FXML private AnchorPane root;

	@FXML private VBox vBxRoot;
//	@FXML private HBox hBxForSelectorAndFilter;
	@FXML private VBox vBxForSelector;
	@FXML private HBox hBxForFilter;

	@FXML private DatePicker dtPckrStart;
	@FXML private DatePicker dtPckrEnd;

	@FXML private Button btnApply;
//	@FXML private Button buttonExit;

	// Inject event dispatchers for manual registration in @PostConstruct.
	// Cannot use @Observes(IF_EXISTS) directly because @Dependent beans don't support conditional observers.
	@Inject private EventDispatcher<                  FXCAppStartedEvent>             appStartedEventDispatcher;
	@Inject private EventDispatcher<TaskGroupSelectorComponentReadyEvent> taskGroupSelectorReadyEventDispatcher;

	// inject components that are used in the user interface
	@Inject private TaskGroupSelector taskGroupSelector;
	@Inject private TaskTreeTable     taskTreeTable;

	// inject service clients that are used to fetch data from the server
	@Inject private TaskGroupServiceClient taskGroupServiceClient;

	// inject the centralized executor for service operations with session retry handling
	@Inject private ServiceOperationExecutor executor;

	private Optional<TaskGroupFlat> selectedTaskGroupDTOFlat = Optional.empty();

	@Override @FXML protected void initialize()
	{
		appStartedEventDispatcher            .add(e -> onAppStarted            (e));
		taskGroupSelectorReadyEventDispatcher.add(e -> onTaskGroupSelectorReady(e));

		// prepare selector
		vBxForSelector.setAlignment(Pos.BOTTOM_LEFT);
		// force task group selector to initialise itself and compose its local root into the ui
		vBxForSelector.getChildren().add(taskGroupSelector.localRoot());

		FXUtil.wrapInTitledBorder("group", (Region) vBxForSelector);

		// prepare filter
		configureDatePickerGermanFormat(dtPckrStart);
		configureDatePickerGermanFormat(dtPckrEnd);

		dtPckrStart.setValue(LocalDate.now());
		dtPckrEnd  .setValue(LocalDate.now());

		btnApply.setOnAction(e -> onApply());
		FXUtil.wrapInTitledBorder("filter", (Region) hBxForFilter);

		// force task tree table to initialise itself and compose its local root into the ui
		vBxRoot.getChildren().add(taskTreeTable.localRoot());
		VBox.setVgrow(taskTreeTable.localRoot(), ALWAYS);
		HBox.setHgrow(taskTreeTable.localRoot(), ALWAYS);
		FXUtil.setAnchorsInAnchorPaneTo(taskTreeTable.localRoot(), 0);

		// buttonExit.setOnAction(e -> onExit());
	}

	/**
	 * Loads initial data from backend after authentication is complete.
	 *
	 * <p>This method is called from DashApp.start() AFTER the user has been authenticated.
	 * It must not be called from initialize() because authentication happens after FXML loading.</p>
	 */
	public void loadInitialData()
	{
		log.info("Loading initial data from backend...");
		fetchTaskGroupsFromBackendAndPopulateTaskGroupSelector();
	}

	private void fetchTaskGroupsFromBackendAndPopulateTaskGroupSelector()
	{
		try
		{
			Set<TaskGroupFlat> groups = executor.execute(
					() -> taskGroupServiceClient.findAllFlat(),
					"fetching task groups",
					"Failed to load task groups",
					"Load failed after re-login"
			);

			// now we are ready to hand over the groups to groupSelector
			taskGroupSelector.service().items(groups);
		}
		catch (TechnicalException | NonTechnicalException e)
		{
			log.error("failure fetching task groups from backend", e);
			ExceptionDialog.showAndWait("failure fetching task groups from backend", e);
		}
	}

	private void onApply()
	{
		taskTreeTable
				.service()
				.populate(taskGroupSelector.service().selectedTaskGroupProperty().get(),
				dtPckrStart.getValue(), dtPckrEnd.getValue());
	}

	/** called when the FX application has started */
	private void onAppStarted(FXCAppStartedEvent e)
	{
		getStage(vBxForSelector).ifPresent(s -> s.setTitle("jeee RAAAH - gantt view"));
	}

	/**
	 * is called as soon as the task group selector is available, performs various initialisations that depend on task
	 * group selector.
	 *
	 * @param e the event that indicates that the groupSelector component is ready
	 */
	private void onTaskGroupSelectorReady(TaskGroupSelectorComponentReadyEvent e)
	{
		@NonNull
		ReadOnlyObjectProperty<TaskGroupFlat> selectedTaskGroupProperty = taskGroupSelector.service()
				.selectedTaskGroupProperty();

		// make sure the listener method is called whenever the selected group in taskGroupSelector changes
		selectedTaskGroupProperty.addListener((obs, old, act) -> onSelectedTaskGroupChanged(act));
	}

	private void onSelectedTaskGroupChanged(TaskGroupFlat actSelection)
	{
		selectedTaskGroupDTOFlat = Optional.ofNullable(actSelection);

		if (isNull(actSelection)) return;

		taskTreeTable.service().populate(actSelection, dtPckrStart.getValue(), dtPckrEnd.getValue());
	}

	/**
	 * Configures a DatePicker to use German date format (dd.MM.yyyy).
	 *
	 * @param datePicker the DatePicker to configure
	 */
	private void configureDatePickerGermanFormat(DatePicker datePicker)
	{
		DateTimeFormatter germanDateFormatter = DateTimeFormatter.ofPattern("dd.MM.yyyy");

		datePicker.setConverter(new StringConverter<LocalDate>() {
			@Override
			public String toString(LocalDate date)
			{
				return date != null ? germanDateFormatter.format(date) : "";
			}

			@Override
			public LocalDate fromString(String string)
			{
				if (string != null && !string.trim().isEmpty())
				{
					try
					{
						return LocalDate.parse(string, germanDateFormatter);
					}
					catch (DateTimeParseException e)
					{
						return null;
					}
				}
				return null;
			}
		});
	}
}