package de.ruu.app.jeeeraaah.frontend.ui.fx.task.gantt;

import static de.ruu.app.jeeeraaah.common.api.domain.Task.COMPARATOR;
import static java.util.Objects.isNull;
import static java.util.Objects.requireNonNull;
import static javafx.scene.control.Alert.AlertType.INFORMATION;
import static javafx.scene.control.SelectionMode.SINGLE;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

import de.ruu.app.jeeeraaah.common.api.bean.TaskBean;
import de.ruu.app.jeeeraaah.common.api.bean.TaskGroupBean;
import de.ruu.app.jeeeraaah.common.api.domain.TaskGroup;
import de.ruu.app.jeeeraaah.common.api.domain.TaskGroupFlat;
import de.ruu.app.jeeeraaah.frontend.api.client.ws.rs.TaskGroupServiceClient;
import de.ruu.lib.fx.comp.FXCController.DefaultFXCController;
import de.ruu.lib.fx.control.dialog.AlertDialog;
import de.ruu.lib.fx.control.dialog.ExceptionDialog;
import de.ruu.lib.util.Time;
import de.ruu.lib.ws.rs.NonTechnicalException;
import de.ruu.lib.ws.rs.TechnicalException;
import jakarta.annotation.Nullable;
import jakarta.inject.Inject;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.value.ChangeListener;
import javafx.fxml.FXML;
import javafx.scene.control.TreeItem;
import javafx.scene.control.TreeTableView;
import lombok.NonNull;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2024.12.22 11:45:01:816
 */
@Slf4j
class TaskTreeTableController extends DefaultFXCController<TaskTreeTable, TaskTreeTableService>
		implements TaskTreeTableService
{
	@FXML
	private TreeTableView<TaskTreeTableDataItem> ttv;

	// inject service clients that are used to fetch data from the server
	@Inject
	private TaskGroupServiceClient taskGroupServiceClient;

	/** updated by callers of #activateTaskGroup() */
	private ObjectProperty<TaskGroupBean> activeTaskGroupProperty = new SimpleObjectProperty<>();

	@Override @FXML
	protected void initialize()
	{
		TreeItem<TaskTreeTableDataItem> rootTreeItem = new TreeItem<>();
		ttv.setRoot(rootTreeItem);
		ttv.setShowRoot(false);

		rootTreeItem.getChildren().addAll(rootTreeItemChildren());

		// Initialize with default columns
		LocalDate defaultStart = LocalDate.of(2025, 1, 1);
		LocalDate defaultEnd = LocalDate.of(2025, 3, 31);
		ttv.getColumns().addAll(columns(defaultStart, defaultEnd));

		// Configure column resize policy for better behavior
		ttv.setColumnResizePolicy(TreeTableView.UNCONSTRAINED_RESIZE_POLICY);

		// Make scrollbar always visible so users know they can scroll back to first column
		ttv.setStyle("-fx-hbar-policy: always;");

		ttv.getSelectionModel().setSelectionMode(SINGLE);
		ttv.getSelectionModel().selectedItemProperty().addListener(selectedItemChangeListener());
	}

	@Override public void populate(@Nullable TaskGroupFlat taskGroup, @NonNull LocalDate start, @NonNull LocalDate end)
	{
		// Clear existing data
		ttv.getRoot().getChildren().clear();

		// Recreate columns for the new date range
		ttv.getColumns().clear();
		ttv.getColumns().addAll(columns(start, end));

		if (isNull(taskGroup)) { return; }

		// fetch the task group with its tasks and their neighbour tasks from the server
		try
		{
			Optional<TaskGroupBean> optional =
					taskGroupServiceClient.findWithTasksAndDirectNeighbours(requireNonNull(taskGroup.id()));

			if (optional.isPresent())
			{
				TaskGroupBean taskGroupBean = optional.get();

				// fetch all of group's tasks together with the ids of their related tasks from the server
				List<TaskBean> mainTasks = new ArrayList<>();

				if (taskGroupBean.tasks().isPresent())
						mainTasks =
								taskGroupBean.tasks().get().stream()
										.filter(taskBean -> taskBean.superTask().isEmpty()) // we do not filter for start and end here
								.collect(Collectors.toList());
				else
				{
					AlertDialog.showAndWait
					(
							"no tasks in group",
							"can not display main tasks when no tasks are available for task group",
							"task group: " + taskGroupBean.name(),
							INFORMATION
					);
				}

				mainTasks.sort(COMPARATOR);

				mainTasks.forEach(mainTask -> ttv.getRoot().getChildren().add(populateTreeNode(mainTask, start, end)));

				log.debug("populate tree table view done");
			}
			else
					log.debug("no lazy group could be retrieved");
		}
		catch (TechnicalException | NonTechnicalException e)
		{
			ExceptionDialog.showAndWait("failure fetching task group from backend", e);
		}
	}

	private TreeItem<TaskTreeTableDataItem> populateTreeNode(TaskBean task, @NonNull LocalDate start, @NonNull LocalDate end)
	{
		return populateTreeNode(task, start, end, new HashSet<>());
	}

	private TreeItem<TaskTreeTableDataItem> populateTreeNode(TaskBean task, @NonNull LocalDate start,
			@NonNull LocalDate end, Set<Long> processedTaskIds)
	{
		// Prevent infinite recursion by tracking already processed tasks
		if (task.id() != null && processedTaskIds.contains(task.id()))
		{
			log.warn("Circular reference detected: Task {} (ID: {}) already in hierarchy - skipping to prevent infinite loop",
					task.name(), task.id());
			return null;
		}

		if (task.id() != null)
		{
			processedTaskIds.add(task.id());
		}

		TaskTreeTableDataItem taskTreeTableDataItem = new TaskTreeTableDataItem(task, start, end);
		TreeItem<TaskTreeTableDataItem> result = new TreeItem<>(taskTreeTableDataItem);
		if (task.subTasks().isPresent())
		{
			task.subTasks().get().forEach(subTask -> {
				TreeItem<TaskTreeTableDataItem> childNode = populateTreeNode(subTask, start, end, processedTaskIds);
				if (childNode != null)
				{
					result.getChildren().add(childNode);
				}
			});
		}
		return result;
	}

	@Inject private DataItemFactory dataItemFactory;

	/** returns a list of task tree table items that are meant as children for the task tree table root */
	private List<TreeItem<TaskTreeTableDataItem>> rootTreeItemChildren()
	{
		TaskGroupBean taskGroup = activeTaskGroupProperty.get();

		if (isNull(taskGroup)) return Collections.emptyList();

		List<TreeItem<TaskTreeTableDataItem>> result = new ArrayList<>();

		LocalDate startOfPeriod = LocalDate.of(2025, 1, 1);
		LocalDate endOfPeriod   = LocalDate.of(2025, 3, 31);

//		DataItemFactory factory = new DataItemFactory(startOfPeriod, endOfPeriod);
		for (TaskTreeTableDataItem rootItem : dataItemFactory.rootItemsInPeriod(taskGroup, startOfPeriod, endOfPeriod))
		{
			TreeItem<TaskTreeTableDataItem> rootTaskAsTreeItem = new TreeItem<>(rootItem);
			result.add(rootTaskAsTreeItem);
			populateRecursively(rootTaskAsTreeItem, startOfPeriod, endOfPeriod);
		}

		result.sort((ti1, ti2) -> ti1.getValue().task().name().compareTo(ti2.getValue().task().name()));

		return result;
	}

	/** returns a list of columns for the tree table view */
	private List<TaskTreeTableColumn> columns(@NonNull LocalDate start, @NonNull LocalDate end)
	{
		List<TaskTreeTableColumn> result = new ArrayList<>();

		// First column: Task names - make it VERY prominent and wide
		TaskTreeTableColumn rootTasksColumn = new TaskTreeTableColumn("root tasks");
		rootTasksColumn.setCellValueFactory(cdfs -> {
			TreeItem<TaskTreeTableDataItem> treeItem = cdfs.getValue();
			TaskTreeTableDataItem tableDataItem = treeItem.getValue();
			TaskBean task = tableDataItem.task();
			return new SimpleStringProperty(task.name());
		});

		// PRAGMATIC SOLUTION: Make first column very wide so it's always visible
		// when window is maximized (most common use case)
		rootTasksColumn.setResizable(true);
		rootTasksColumn.setPrefWidth(400);   // Very wide (was 300)
		rootTasksColumn.setMinWidth(200);    // Generous minimum
		rootTasksColumn.setMaxWidth(600);    // Can grow even more

		// Cannot be moved
		rootTasksColumn.setReorderable(false);

		// Strong visual distinction with darker background and thick border
		rootTasksColumn.setStyle(
		    "-fx-background-color: #e8e8e8; " +        // Darker gray (was #f9f9f9)
		    "-fx-border-width: 0 3 0 0; " +            // Thicker border (was 2)
		    "-fx-border-color: #999999; " +            // Darker border (was #cccccc)
		    "-fx-font-weight: bold;"                   // Bold text for emphasis
		);

		rootTasksColumn.getStyleClass().add("frozen-column");
		result.add(rootTasksColumn);

		// Date columns - keep narrow (30px each is fine)
		for (LocalDate date : Time.datesInPeriod(start, end.plusDays(1)))
		{
			TaskTreeTableColumn ttc = new TaskTreeTableColumn(date);
			result.add(ttc);
		}
		return result;
	}

	/**
	 * Populates tree item children of {@code parentTreeItem} with tree items for each child of the {@link TaskBean} value
	 * from {@code parentTreeItem}.
	 */
	private void populateRecursively
			(TreeItem<TaskTreeTableDataItem> parentTreeItem, LocalDate startOfPeriod, LocalDate endOfPeriod)
	{
		TaskBean parentTaskBean = parentTreeItem.getValue().task();

		if (parentTaskBean.subTasks().isPresent())
		{
			List<TaskBean> subTasks = new ArrayList<>(parentTaskBean.subTasks().get());
			subTasks.sort((tb1, tb2) -> tb1.name().compareTo(tb2.name()));

			for (TaskBean subTask : subTasks)
			{
				TaskTreeTableDataItem dataItem = new TaskTreeTableDataItem(subTask, startOfPeriod, endOfPeriod);
				TreeItem<TaskTreeTableDataItem> treeItemChild = new TreeItem<>(dataItem);
				parentTreeItem.getChildren().add(treeItemChild);
				populateRecursively(treeItemChild, startOfPeriod, endOfPeriod);
			}
		}
	}

	private ChangeListener<? super TreeItem<TaskTreeTableDataItem>> selectedItemChangeListener()
	{
		return (ChangeListener<TreeItem<TaskTreeTableDataItem>>) (obs, old, newValue) -> log.debug("\nold: {}\nnew: {}",
				old == null ? "" : old.getValue().task().name(), newValue == null ? "" : newValue.getValue().task().name());
	}
}
