package de.ruu.app.jeeeraaah.frontend.ui.fx.task.gantt;

import de.ruu.app.jeeeraaah.common.api.bean.TaskGroupBean;
import de.ruu.app.jeeeraaah.common.api.domain.TaskGroupFlat;
import de.ruu.lib.fx.comp.FXCService;
import jakarta.annotation.Nullable;
import lombok.NonNull;

import java.time.LocalDate;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2024.12.22 11:45:01:813
 */
public interface TaskTreeTableService extends FXCService
{
	void populate(@Nullable TaskGroupFlat taskGroup, @NonNull LocalDate start, @NonNull LocalDate end);
}