package de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.predecessor;

import static de.ruu.lib.util.BooleanFunctions.not;
import static java.util.Objects.isNull;
import static javafx.geometry.NodeOrientation.RIGHT_TO_LEFT;
import static javafx.scene.control.Alert.AlertType.ERROR;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import de.ruu.app.jeeeraaah.common.api.bean.TaskBean;
import de.ruu.app.jeeeraaah.frontend.api.client.ws.rs.TaskServiceClient;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.TaskHierarchyControllerAbstract;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.predecessor.add.ActionAdd;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.predecessor.add.ActionAdd.Context;
import de.ruu.lib.fx.control.dialog.AlertDialog;
import de.ruu.lib.fx.control.dialog.ExceptionDialog;
import de.ruu.lib.ws_rs.NonTechnicalException;
import de.ruu.lib.ws_rs.TechnicalException;
import jakarta.annotation.Nullable;
import jakarta.inject.Inject;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.TreeItem;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2025.06.03 12:49:45:376
 */
@Slf4j
class TaskHierarchyPredecessorsController extends TaskHierarchyControllerAbstract
		implements TaskHierarchyPredecessorsService
{
	@Inject private TaskServiceClient taskServiceClient;

	private ObjectProperty<TreeItem<TaskBean>> selectedSuperSubTaskTreeItemProperty = new SimpleObjectProperty<>();
	private ObjectProperty<TreeItem<TaskBean>> selectedPredecessorTreeItemProperty  = new SimpleObjectProperty<>();

	@Override @FXML protected void initialize()
	{
		super.initialize();

		treeView().setNodeOrientation(RIGHT_TO_LEFT);
		treeView().getSelectionModel().selectedItemProperty()
				.addListener((obs, old, act) -> selectedPredecessorTreeItemProperty.set(act));

		buttonAdd   ().disableProperty()
				.bind(selectedSuperSubTaskTreeItemProperty.isNull().and(selectedPredecessorTreeItemProperty.isNull()));
		buttonRemove().disableProperty()
				.bind(selectedSuperSubTaskTreeItemProperty.isNull().and(selectedPredecessorTreeItemProperty.isNull()));

		buttonAdd   ().setOnAction(e -> onAdd(e));
		buttonRemove().setOnAction(e -> onRemove(e));
	}

	@Override public void selectedSuperSubTaskTreeItemChanged(@Nullable TreeItem<TaskBean> selectedSuperSubTaskTreeItem)
	{
		selectedSuperSubTaskTreeItemProperty.set(selectedSuperSubTaskTreeItem);

		treeView().getRoot().getChildren().clear(); // clear the predecessor tree view
		taskView.service().unpopulateView();

		if (isNull(selectedSuperSubTaskTreeItem))
				return;

		if (selectedSuperSubTaskTreeItem.getValue().predecessors().isPresent())
		{
			Set<TaskBean> predecessors = selectedSuperSubTaskTreeItem.getValue().predecessors().get();
			predecessors.forEach
			(
					predecessor -> treeView().getRoot().getChildren().add(populateTreeNode(treeView().getRoot(), predecessor))
			);
		}
	}

	@Override protected void onAdd(ActionEvent e)
	{
		if (isNull(selectedSuperSubTaskTreeItemProperty.get()) && isNull(selectedPredecessorTreeItemProperty.get()))
		{
			AlertDialog.showAndWait
			(
					"can not add predecessor relation",
					"no predecessor nor super/sub task is selected",
					"select a predecessor and/or\na super/sub task as target\nfor the new predecessor relation",
					ERROR
			);
			return;
		}

		new ActionAdd
		(
				new Context
				(
						selectedSuperSubTaskTreeItemProperty.get(),
						selectedPredecessorTreeItemProperty.get() == null
								? treeView().getRoot()
								: selectedPredecessorTreeItemProperty.get(),
						taskServiceClient
				)
		).execute();
	}

	@Override protected void onRemove(ActionEvent e)
	{
		if (isNull(selectedPredecessorTreeItemProperty.get()))
		{
			AlertDialog.showAndWait
			(
					"can not remove predecessor relation",
					"no predecessor task is selected",
					"select a predecessor task to be removed",
					ERROR
			);
			return;
		}

		TaskBean selectedPredecessor = selectedPredecessorTreeItemProperty.get().getValue();

		if (    selectedPredecessor.predecessors().isPresent() &&
		    not(selectedPredecessor.predecessors().get().isEmpty()))
		{
			AlertDialog.showAndWait
			(
					"can not remove predecessor relation",
					"the selected predecessor task has predecessor relations",
					"remove the predecessor relations first, then you can remove this predecessor relation",
					ERROR
			);
			return;
		}

		if (selectedPredecessor.successors().isPresent())
		{
			Exception exception = null;
			// remove selected predecessor for all it's successors
			for (TaskBean successor : selectedPredecessor.successors().get())
			{
				// - remove the predecessor-successor relation in the db
				try
				{
					taskServiceClient.removePredecessor(successor, selectedPredecessor);
				}
				catch (TechnicalException | NonTechnicalException ex)
				{
					exception = ex;
					break;
				}
			}

			if (not(isNull(exception)))
			{
				ExceptionDialog.showAndWait("failure removing predecessor", exception);
				return;
			}

			// remove the predecessor-successor relation in the ui model
			TreeItem<TaskBean> parent = selectedPredecessorTreeItemProperty.get().getParent();
			if (parent != null) parent.getChildren().remove(selectedPredecessorTreeItemProperty.get());
		}
	}

	@Override protected TreeItem<TaskBean> populateTreeNode(TreeItem<TaskBean> root, TaskBean task)
	{
		return populateTreeNode(root, task, new HashSet<>());
	}

	private TreeItem<TaskBean> populateTreeNode(TreeItem<TaskBean> root, TaskBean task, Set<Long> processedTaskIds)
	{
		// Prevent infinite recursion by tracking already processed tasks
		if (task.id() != null && processedTaskIds.contains(task.id()))
		{
			log.warn("Circular reference detected: Task {} (ID: {}) already in hierarchy - skipping to prevent infinite loop",
					task.name(), task.id());
			return null;
		}

		if (task.id() != null)
		{
			processedTaskIds.add(task.id());
		}

		TreeItem<TaskBean> result = new TreeItem<>(task)
		{
			@Override public String toString() { return task.name(); }
		};
		task.predecessors().ifPresent(predecessors -> populateTreeNode(result, predecessors, processedTaskIds));
		return result;
	}

	private void populateTreeNode(TreeItem<TaskBean> parent, Set<TaskBean> children)
	{
		populateTreeNode(parent, children, new HashSet<>());
	}

	private void populateTreeNode(TreeItem<TaskBean> parent, Set<TaskBean> children, Set<Long> processedTaskIds)
	{
		List<TaskBean> childrenAsList = new ArrayList<>(children);
		childrenAsList.sort((o1, o2) -> o1.name().compareTo(o2.name()));
		childrenAsList.forEach(child -> {
			TreeItem<TaskBean> childNode = populateTreeNode(parent, child, processedTaskIds);
			if (childNode != null)
			{
				parent.getChildren().add(childNode);
			}
		});
	}
}